import { Task } from "@/utils/types";

export const initialTasks: Task[] = [
  {
    id: 1,
    columnId: 1,
    name: "Task 1",
    description: "This is the first task",
    status: false,
  },
  {
    id: 2,
    columnId: 1,
    name: "Task 2",
    description: "This is the second task",
    status: false,
  },
  {
    id: 3,
    columnId: 1,
    name: "Task 3",
    description: "This is the third task",
    status: false,
  },
  {
    id: 4,
    columnId: 2,
    name: "Task 4",
    description: "This is the fourth task",
    status: false,
  },
  {
    id: 5,
    columnId: 2,
    name: "Task 5",
    description: "This is the fifth task",
    status: false,
  },
  {
    id: 6,
    columnId: 2,
    name: "Task 6",
    description: "This is the sixth task",
    status: false,
  },
  {
    id: 7,
    columnId: 3,
    name: "Task 7",
    description: "This is the seventh task",
    status: false,
  },
  {
    id: 8,
    columnId: 3,
    name: "Task 8",
    description: "This is the eighth task",
    status: false,
  },
  {
    id: 9,
    columnId: 3,
    name: "Task 9",
    description: "This is the ninth task",
    status: false,
  },
  {
    id: 10,
    columnId: 5,
    name: "Task 10",
    description: "This is the tenth task",
    status: false,
  },
  {
    id: 11,
    columnId: 5,
    name: "Task 11",
    description: "This is the eleventh task",
    status: false,
  },
  {
    id: 12,
    columnId: 5,
    name: "Task 12",
    description: "This is the twelfth task",
    status: false,
  },
  {
    id: 13,
    columnId: 4,
    name: "Task 13",
    description: "This is the thirteenth task",
    status: false,
  },
  {
    id: 14,
    columnId: 4,
    name: "Task 14",
    description: "This is the fourteenth task",
    status: false,
  },
  {
    id: 15,
    columnId: 4,
    name: "Task 15",
    description: "This is the fifteenth task",
    status: false,
  },
  {
    id: 16,
    columnId: 6,
    name: "Task 16",
    description: "This is the sixteenth task",
    status: false,
  },
  {
    id: 17,
    columnId: 6,
    name: "Task 17",
    description: "This is the seventeenth task",
    status: true,
  },
  {
    id: 18,
    columnId: 6,
    name: "Task 18",
    description: "This is the eighteenth task",
    status: true,
  },
];
